version: '3'
services:

  mytester:
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512m
    build:
      context: .
    ports:
      - "8080-8082:8080"
      - "8000-8002:8000"
      - "5701-5703:5701"

  cassandra:
    image: scylladb/scylla
    ports:
      - "9042:9042"