package com.capgemini.testhz.train

object ExampleStationsOportoLisbon {
    val list = listOf(
        "Porto - Campanhã",
        "Gaia - General Torres",
        "Gaia - Devesas",
        "Coimbrões",
        "Madalena",
        "Valadares",
        "Francelos",
        "Miramar",
        "Aguda",
        "Granja",
        "Espinho",
        "Paramos",
        "Esmoriz",
        "Ovar",
        "Avanca",
        "Estarreja",
        "Cacia",
        "Aveiro",
        "Oliveira do Bairro",
        "Mogofores",
        "Mealhada",
        "Pampilhosa",
        "Coimbra-B",
        "Alfarelos",
        "Soure",
        "Pombal",
        "Caxarias",
        "Fátima",
        "Lamarosa",
        "Entroncamento",
        "Riachos",
        "Mato de Miranda",
        "Vale de Figueira",
        "Santarém",
        "Vale de Santarém",
        "Santana-Cartaxo",
        "Setil",
        "Reguengo-V.Pedra-Pontevel",
        "Virtudes",
        "Azambuja",
        "Espadanal da Azambuja",
        "Vila Nova da Rainha",
        "Carregado",
        "Castanheira do Ribatejo",
        "Vila Franca de Xira",
        "Alhandra",
        "Alverca",
        "Povoa",
        "Santa Iria",
        "Bobadela",
        "Sacavém",
        "Moscavide",
        "Lisboa - Oriente",
        "Braço de Prata",
        "Lisboa - Santa Apolónia"
    )
}